rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672" #JMS Port
    - "15672:15672" #Management Port - default user:pass = guest:guest

JavaUserInfo:
  image: docker-java-image
  ports:
    #  local : container expose
    - "8080:8080"
